@startuml creation_of_new_report
    participant User as U
    participant System as S
    participant Storage as ST

    autoactivate on

    U -> S: 1.get_report_violation\n_page()
    return
    U -> S: 2.send_report(report)
    S -> ST: 2.1.check_user_credentials()
    return user data
    S -> S: 2.2.report_is_valid(report)
    deactivate S
    S -> ST: 2.3store_report(report)
    return ok
    return ok, redirect\nto main page
@enduml

@startuml information_mining
    participant User as U
    participant System as S
    participant Storage as ST

    autoactivate on

    U -> S: 1.get_statistics_page()
    S -> ST: 1.1.check_user_type()
    return user
    return filters
    U -> S: 2.send_filters(filters)
    S -> ST: 2.1.query(filters)
    return search results
    S -> S: 2.2.process_results()
    deactivate S
    return unsafe areas
    U -> S: 3.get main page
    return main page
@enduml

@startuml information_mining_by_officers
    participant User as U
    participant System as S
    participant Storage as ST

    autoactivate on

    U -> S: 1.get_statistics_page()
    S -> ST: 1.1.check_user_type()
    return authority
    return filters
    U -> S: 2.send_filters(filters)
    S -> ST: 2.1.query(filters)
    return search results
    S -> S: 2.2.process_results()
    deactivate S
    return unsafe areas
    U -> S: 3.get main page
    return main page
@enduml

@startuml automatic_traffic_ticket
    participant User as U
    participant SafeStreet as S
    participant Police as P

    autoactivate on

    U -> S: 1.get_report_violation\n_page()
    return
    U -> S: 2.send_report(report)
    S -> S: 2.1.check_user_credentials()
    deactivate S
    S -> S: 2.2.report_is_valid(report)
    deactivate S
    S -> S: 2.3.store_report_verified(report)
    deactivate S
    S -> S : 2.4 store_hash(report)
    deactivate S
    S -> P: 2.5.send_report(report)
    P -> P: 2.6.calc_hash(report)
    deactivate P
    P -> S : 2.7.check_hash(hash)
    return ok
    P -> P: 2.8.process\n_ticket(ticket)
    deactivate P
    return ok
    return ok, redirect\nto main page
@enduml

@startuml information_mining_vehicle
    participant User as U
    participant System as S
    participant Storage as ST

    autoactivate on

    U -> S: 1.get_statistics_page()
    S -> ST: 1.1check_user_type()
    return user
    return filters
    U -> S: 2.send_filters(filters)
    S -> ST: 2.1.query(filters)
    return search results
    S -> S: 2.2.process_results()
    deactivate S
    return vehicles statistics
    U -> S: 3.get main page
    return main page
@enduml

@startuml mining_vehicle_officers
    participant User as U
    participant System as S
    participant Storage as ST

    autoactivate on

    U -> S: 1.get_statistics_page()
    S -> ST: 1.1.check_user_type()
    return authority
    return filters
    U -> S: 2.send_filters(filters)
    S -> ST: 2.1.query(filters)
    return search results
    S -> S: 2.2.process_results()
    deactivate S
    return vehicle statistics
    U -> S: 3.get main page
    return main page
@enduml