@startuml sign_up
    autoactivate on

    participant User as U
    participant System as S
    participant Storage as ST

    activate U
    U -> S: 1.get_signup_page()
    return
    U -> S: 2.send_user_data(data)
    S -> S: 2.1.check_validity(data)
    deactivate S
    S -> ST: 2.2.store_data(data)
    return ok
    return ok, redirect to\nprofile page
    deactivate U
@enduml

@startuml login
    autoactivate on

    participant User as U
    participant System as S
    participant Storage as ST

    activate U
    U -> S: 1.get_login_page()
    return login page
    U -> S: 2.send_login\n_information(data)
    S -> ST: 2.1.check_login_info(data)
    return user data
    return ok, redirect\nto homepage
    deactivate U
@enduml

@startuml password_recovery
    autoactivate on

    participant User as U
    participant System as S
    participant Storage as ST
    participant Mailer as M

    activate U
    U -> S: 1.get_login_page()
    return login page
    U -> S: 2.get_passw_recovery_page()
    return password recovery page
    U -> S: 3.recover_passw(email)
    deactivate U
    S -> ST: 3.1.check_user_exists(email)
    return user data
    S -> M: 3.2.send_recovery_email(email)
    deactivate S
    M ->> U: email with link to recover password
    deactivate M
    activate U
    U -> S: 4.set_new_passwd(password)
    S -> ST: 4.1.update_password\n(email, password)
    return ok
    return ok, redirect to login page
    deactivate U

@enduml