@startuml Sign Up
    autoactivate on

    participant User as U
    participant System as S
    participant Storage as ST

    activate U
    U -> S: get signup page
    return send sigup page
    U -> S: send email, password\n & profile pic
    S -> S: check data\nis valid
    deactivate S
    S -> ST: store data
    return ok
    return ok, redirect to\nprofile page
    deactivate U
@enduml

@startuml Login
    autoactivate on

    participant User as U
    participant System as S
    participant Storage as ST

    activate U
    U -> S: get login page
    return login page
    U -> S: send login\ninformation
    S -> ST: check login info
    return user data
    return ok, redirect\nto homepage
    deactivate U
@enduml

@startuml Password Recovery
    autoactivate on

    participant User as U
    participant System as S
    participant Storage as ST
    participant Mailer as M

    activate U
    U -> S: get login page
    return login page
    U -> S: recover password
    return password recovery page
    U -> S: send email used to login
    deactivate U
    S -> ST: check user exists
    return user data
    S -> M: send email\nto user
    deactivate S
    M ->> U: email with link\nto recover password
    deactivate M
    activate U
    U -> S: set new password
    return redirect to login page
    deactivate U

@enduml