@startuml general_statistics
    participant User as U
    participant System as S

    autoactivate on

    U -> S: 1.get_statistics_page()
    return filters
    U -> S: 2.send_filters(filters)
    S -> S: 2.1.query(filters)
    deactivate S
    S -> S: 2.2.process_results()
    deactivate S
    return general statistics
    U -> S: 3.get main page
    return main page
@enduml