@startuml uc_user_page
    left to right direction
    skinparam packageStyle rectangle

    actor Guest as G
    actor User as U
    rectangle "user pages" {
        G -- (Sign Up)
        U -- (Login)
        U -- (Recover password)
        U -- (Change password)
        U -- (Edit profile picture)
        U -- (View my reports)
    }
@enduml

@startuml uc_report_and_information_mining
    left to right direction
    skinparam packageStyle rectangle

    actor User as U
    actor Officer as O

    rectangle "Reports and information mining" {
        (Create report) as CR
        (Give ticket) as GT
        (Mine information) as MI
        (Mine unsafe areas for User) as MIUAU
        (Mine vehicle violations for User) as MVVU
        (Mine unsafe areas for Officer) as MIUAO
        (Mine vehicle violations for Officer) as MVVO

        U -- CR
        U -- MIUAU
        U -- MVVU
        O -- MIUAO
        O -- MVVO
        CR <. GT : <<extend>>
        MIUAU --|> MI
        MVVU --|> MI
        MIUAO --|> MI
        MVVO --|> MI
    }
@enduml

@startuml uc_statistics
    left to right direction
    skinparam packageStyle rectangle

    actor Officer as O
    actor User as U
    rectangle "user pages" {
        U -- (See Statistics)
        O -- (See Statistics)
    }
@enduml