@startuml uc_user_page
    left to right direction
    skinparam packageStyle rectangle

    actor User as U
    rectangle "user pages" {
        U -- (Sign Up)
        U -- (Login)
        U -- (Recover password)
        U -- (Change password)
        U -- (Edit profile picture)
    }
@enduml

@startuml uc_report_and_information_mining
    left to right direction
    skinparam packageStyle rectangle

    actor User as U
    actor Officer as O

    rectangle "Reports and information mining" {
        (Create report) as CR
        (Give ticket) as GT
        (Mine information) as MI
        (Mine information for User) as MIU
        (Mine information for Officer) as MIO

        U -- CR
        U -- MIU
        O -- MIO
        CR <. GT : <<extend>>
        MIU --|> MI
        MIO --|> MI
    }
@enduml